name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOLACHE_E58FA }}
          channelId: live
          projectId: kolache-e58fa

  database-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w9jds/firebase-action@v15.18.0
        with:
          args: deploy --only database --project kolache-e58fa --non-interactive
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOLACHE_E58FA }}
          PROJECT_ID: kolache-e58fa
